### ISSUE TITLE
Feiner Code

### ISSUE THREAD

**Issue by PaulFelz** [ammendola/Aufgabe_MALIS_18.3_WPM_T9.2#3]
Heidiho werter Tandempartner,

sorry das ich so spät dran bin.

Habe mir deinen Code angesehen... da ist zu dem was du beabsichtigst nichts was ich dir noch in irgendeiner Form verbessern oder auch nur anmerken könnte.
Im Gegenteil, ich werde mit Freuden deinen Code als Inspiration verwenden.
Gerade wenn ich os.stats Abfrage und damit arbeite, damit ich nur neue/aktualisierte Dateien backuppe kann ich mir bei dir hier unter dem Punkt "filetoobig" einige Kleinigkeiten abgucken. Sehr schönes Ding! 

Viel Freude im Urlaub, erhol dich gut und genieß das Wetter!
Wünsche dir alles Gute! Auf bald!!!
Sogar gewissenhafte Kommentare, die helfen deinen Code zu verstehen hast du eingefügt... 
Bester!!! :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by ammendola** [comment]
Danke, mein Bester Tandempartner!

Ein so tolles Lob von Dir erfüllt mein Herz mit Freude!

Danke sehr und viel Freude noch bei Deinem Code!

Viele Grüße und bis bald (spätestens im November)
Andrea
